<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="chinmayee" failures="2" tests="12" name="com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map" time="2.111" errors="0" timestamp="2022-05-20T18:05:04 IST" skipped="0">
  <testcase classname="com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map" name="CheckFileNotFound" time="0.002">
    <failure message="expected [500] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map.CheckFileNotFound(TC_002_get_row_all_files_map.java:345)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CheckFileNotFound -->
  <system-out/>
  <testcase classname="com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map" name="CheckAutofillMissing" time="1.264"/>
  <system-out/>
  <testcase classname="com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map" name="checkRowCount" time="0.011"/>
  <system-out/>
  <testcase classname="com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map" name="checkResposeBody" time="0.001"/>
  <system-out/>
  <testcase classname="com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map" name="checkmessage" time="0.007"/>
  <system-out/>
  <testcase classname="com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map" name="checkcolumns" time="0.008"/>
  <system-out/>
  <testcase classname="com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map" name="CheckBadRequest" time="0.003">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map.CheckBadRequest(TC_002_get_row_all_files_map.java:332)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CheckBadRequest -->
  <system-out/>
  <testcase classname="com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map" name="checkstatusLine" time="0.002"/>
  <system-out/>
  <testcase classname="com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map" name="checkSortcolumn" time="0.125"/>
  <system-out/>
  <testcase classname="com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map" name="checkResponseTime" time="0.002"/>
  <system-out/>
  <testcase classname="com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map" name="checkStatusCode" time="0.001"/>
  <system-out/>
  <testcase classname="com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map" name="CheckSummary" time="0.685"/>
  <system-out/>
</testsuite> <!-- com.weavapi.testCases.Data_Browser_API.TC_002_get_row_all_files_map -->
